apiVersion: v1 
kind: Pod
metadata: 
  name: secret-test-pod
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-db-secret
          key: db-pass